// "How do I...?" help for the Orb. Short, step-by-step answers written from the app's own
// screens and buttons, so staff can ask in their own words and get the steps.
//
// Names in quotes are the real menu items and buttons. If a screen is renamed, change it
// here (scripts/verify-orb-help.mjs checks every article is well formed and findable).
//
// Fields:
//   id        unique, kebab-case
//   title     what it answers, as a sentence
//   topic     the group it belongs to (for "what can you help with")
//   asks      ways people might ask it (used for matching; add the awkward real ones)
//   keywords  single words that point to it
//   needs     the permission a person needs to do it (omit if everyone can)
//   where     'desktop' | 'phone' | 'both'
//   steps     the steps, in order
//   tip       one useful extra line (optional)
//   open      { label, route } a button that takes them there (optional)
//   related   ids of articles to suggest next
//
// Facts here must be true of the app today. Where a feature is built but not switched on,
// the article says so.

export const HELP_CHECKED = "2026-10-10";

export const HELP_ARTICLES = [
  // ---- stock -----------------------------------------------------------------------------
  {
    id: "add-stock-item",
    title: "Add a new product to stock, or record a delivery of something new",
    topic: "Stock",
    asks: ["how do i add a new stock item", "add a new product", "book in a delivery", "record a delivery of something new", "put new stock on the system", "add stock", "add an item to inventory"],
    keywords: ["add", "new", "product", "item", "stock", "delivery", "book", "inventory"],
    needs: "inventory.write",
    where: "desktop",
    steps: [
      "Go to Inventory and press \"Add item\".",
      "Start typing the product name in the first box, for example \"eclipse\". Primovex suggests products you have had before. Pick one if it's the same, then press \"Receive into it instead\" so you don't create a duplicate.",
      "Or scan the delivery barcode (box or pack) in the scan box at the top, and it fills in what it can.",
      "Fill in the quantity, batch number and expiry date from the box. Choose the Site and Location from the lists.",
      "Save. The window stays open so you can add the next item from the same delivery.",
    ],
    tip: "Every batch keeps its own expiry date, and stock is used soonest-expiring first.",
    open: { label: "Open Inventory", route: "/inventory" },
    related: ["receive-delivery", "scan-barcode", "move-stock-to-kit"],
  },
  {
    id: "receive-delivery",
    title: "Receive a delivery of something we already stock",
    topic: "Stock",
    asks: ["how do i receive a delivery", "book in stock we already have", "add more stock to an existing item", "stock has arrived", "receive an order", "goods in", "increase the stock level"],
    keywords: ["receive", "delivery", "arrived", "order", "restock", "increase", "goods"],
    needs: "inventory.write",
    where: "desktop",
    steps: [
      "Go to Inventory and find the item (use the search box if you need to).",
      "Press \"+ Receive\" on its card.",
      "Enter the quantity, and the batch number and expiry date from the box. If the item has no barcode recorded yet you can add the one on the box.",
      "Save. The new batch is added alongside any existing ones.",
    ],
    tip: "Receiving stock into an archived item brings it back.",
    open: { label: "Open Inventory", route: "/inventory" },
    related: ["add-stock-item", "use-stock", "scan-barcode"],
  },
  {
    id: "use-stock",
    title: "Record stock being used",
    topic: "Stock",
    asks: ["how do i record using stock", "take stock out", "reduce the stock level", "i used some stock", "book out stock", "stock used"],
    keywords: ["use", "used", "take", "reduce", "out", "book"],
    needs: "inventory.write",
    where: "desktop",
    steps: [
      "Go to Inventory and find the item.",
      "Press \"- Use\" on its card.",
      "Enter the quantity and choose a reason (routine use, expired or damaged, stock audit or other).",
      "Save. Primovex takes it from the soonest-expiring batch first.",
    ],
    open: { label: "Open Inventory", route: "/inventory" },
    related: ["receive-delivery", "move-stock-to-kit"],
  },
  {
    id: "scan-barcode",
    title: "Scan a barcode to find or receive a product",
    topic: "Stock",
    asks: ["how do i scan a barcode", "scan a product", "find a product by barcode", "barcode does not match", "scan the box"],
    keywords: ["scan", "barcode", "gs1", "code"],
    needs: "inventory.read",
    where: "both",
    steps: [
      "On a computer: in \"Add item\", scan into the box that says \"Scan the delivery barcode (box or pack)\".",
      "On the phone: open the Primovex app, go to the \"Scan\" tab and point the camera at the barcode.",
      "Primovex reads the product details from the code. A single pack and the box it came in have different codes but belong to the same product, and it knows that.",
    ],
    tip: "If a barcode isn't recognised, search for the product by name and receive it that way; the barcode is saved so it works next time.",
    open: { label: "Open Inventory", route: "/inventory" },
    related: ["add-stock-item", "receive-delivery"],
  },
  {
    id: "move-stock-to-kit",
    title: "Move stock from the store room into a kit or box",
    topic: "Stock",
    asks: ["how do i move stock into a kit", "i took adrenaline from the store room and put it in the anaphylaxis box", "put stock in the emergency bag", "move stock to a location", "transfer stock", "update the location of stock"],
    keywords: ["move", "transfer", "kit", "box", "bag", "location", "store", "room"],
    needs: "inventory.write",
    where: "desktop",
    steps: [
      "Go to Inventory and find the item.",
      "Press \"Locations\" on its card.",
      "Next to where it is now (for example the main store), press \"Move\".",
      "Choose where it's going: an emergency kit, an anaphylaxis box, or a room or equipment. Enter the quantity.",
      "Confirm. The store loses that quantity and the kit gains it.",
    ],
    tip: "This is how you record taking something from the store and putting it in a kit, so the stock levels stay right in both places.",
    open: { label: "Open Inventory", route: "/inventory" },
    related: ["manage-kit", "use-stock"],
  },
  {
    id: "reorder-stock",
    title: "Ask for more of something to be ordered",
    topic: "Stock",
    asks: ["how do i reorder", "request a reorder", "we are running low what do i do", "order more stock", "ask for stock to be ordered"],
    keywords: ["reorder", "order", "running", "low", "request"],
    needs: "inventory.write",
    where: "desktop",
    steps: [
      "Go to Inventory and find the item.",
      "Press \"Reorder\" on its card.",
      "Check the quantity and supplier, add a note if needed, and send the request.",
      "The Reorder Centre in the left menu shows requests that are waiting.",
    ],
    open: { label: "Open Reorder Centre", route: "/reorder-centre" },
    related: ["receive-delivery"],
  },
  {
    id: "stock-photo",
    title: "Add or change a photo of a stock item",
    topic: "Stock",
    asks: ["how do i add a photo to a stock item", "take a picture of a product", "change the photo", "remove a photo"],
    keywords: ["photo", "picture", "image", "camera"],
    needs: "inventory.write",
    where: "desktop",
    steps: [
      "Go to Inventory and find the item.",
      "Press \"Photo\" on its card (or \"Replace\" if it already has one) and choose or take the picture.",
      "To take it off, press \"Remove\" next to the photo.",
    ],
    open: { label: "Open Inventory", route: "/inventory" },
    related: ["add-stock-item"],
  },
  {
    id: "archive-delete-item",
    title: "Archive or permanently delete a stock item",
    topic: "Stock",
    asks: ["how do i delete a stock item", "remove an item from stock", "archive a product", "get rid of an item", "restore an archived item", "delete permanently"],
    keywords: ["archive", "delete", "remove", "restore", "permanently"],
    needs: "inventory.write",
    where: "desktop",
    steps: [
      "To archive (hide it but keep its history): go to Inventory, find the item and press the archive icon on its card. It asks you first. Archived items are hidden; use the archived-items toggle to show them, and \"Restore\" to bring one back.",
      "To delete for good: only people given the permanent-delete permission see \"Delete permanently\". It asks you to type the item's name to confirm, and it can't be undone.",
    ],
    tip: "Archive is almost always the right choice, because it keeps the stock history. If you need permanent delete and can't see it, ask an administrator.",
    open: { label: "Open Inventory", route: "/inventory" },
    related: ["add-role"],
  },
  {
    id: "expiry-warning-days",
    title: "Change how soon before expiry Primovex warns about stock",
    topic: "Stock",
    asks: ["how do i change the expiry warning", "how many days before expiry does it warn", "change the expiry alert window", "expiry warning period", "expiring soon setting"],
    keywords: ["expiry", "warning", "window", "days", "soon", "alert", "setting"],
    needs: "admin.manageSettings",
    where: "desktop",
    steps: [
      "Go to Alerts in the left menu and open its Settings.",
      "Set the number of days before expiry that counts as \"expiring soon\". The default is 30 days. You can set a different number for a category, for example vaccines.",
      "Save. The Alerts page, the stock cards, the desktop pop-up and the Orb all use the same setting.",
    ],
    open: { label: "Open Alerts", route: "/alerts" },
    related: ["add-stock-item"],
  },

  // ---- kits and boxes -----------------------------------------------------------------------------
  {
    id: "manage-kit",
    title: "Add or change what's in an emergency kit or anaphylaxis box",
    topic: "Kits and boxes",
    asks: ["how do i add an item to the anaphylaxis box", "change what is in a kit", "set up a new emergency box", "edit the contents of the resus trolley", "add a box", "manage a kit"],
    keywords: ["kit", "box", "contents", "manage", "trolley", "anaphylaxis", "emergency", "resus"],
    needs: "inventory.delete",
    where: "desktop",
    steps: [
      "Go to Inventory and open \"Anaphylaxis Emergency Boxes\" or \"Emergency Drugs & Equipment (Monthly)\".",
      "Choose the box, then press \"Manage\". To make a new one press \"Add box\".",
      "To add an item, start typing its name and choose it from your stock. Its barcode, batch and expiry fill in for you.",
      "Choose which batch goes in the kit: follow the soonest-expiring batch in stock (it updates itself), or pick a specific one.",
      "Save the changes.",
    ],
    tip: "Items you pick from stock stay linked to it, so the kit shows the right batch and expiry automatically.",
    open: { label: "Open Inventory", route: "/inventory?tab=anaphylaxis" },
    related: ["check-kit-phone", "print-box-label"],
  },
  {
    id: "check-kit-phone",
    title: "Check an emergency kit or anaphylaxis box on the phone",
    topic: "Kits and boxes",
    asks: ["how do i check the anaphylaxis box", "do the monthly emergency check", "check the crash trolley", "scan the box label", "start a kit check", "how do i do the emergency drugs check"],
    keywords: ["check", "kit", "box", "monthly", "scan", "label", "trolley", "reconcile"],
    needs: "inventory.verify",
    where: "phone",
    steps: [
      "Open the Primovex app and scan the QR label on the box (use the \"Scan\" tab, or the phone's camera). The check starts straight away.",
      "Go through the items one at a time. Press \"Present\" (it moves to the next one), or mark one \"Missing\", \"Expired\" or \"Not required\".",
      "For anything that needs dealing with: \"Replace\" swaps it for a new one (pick a batch from stock or type its batch and expiry), \"Message\" sends a note to a colleague, \"Later\" sets a reminder for later today, tomorrow morning or next week.",
      "At the end press \"Review and save\".",
    ],
    tip: "The check is saved as an audit record. Use the notes to explain anything missing or replaced.",
    open: { label: "Open the boxes", route: "/inventory?tab=anaphylaxis" },
    related: ["manage-kit", "print-box-label"],
  },
  {
    id: "print-box-label",
    title: "Print the QR label for a box, or its contents list",
    topic: "Kits and boxes",
    asks: ["how do i print the qr code for a box", "print a label for the kit", "print the contents list", "get the box label", "new qr label"],
    keywords: ["print", "label", "qr", "contents", "list"],
    needs: "inventory.read",
    where: "desktop",
    steps: [
      "Go to Inventory and open the box's tab (\"Anaphylaxis Emergency Boxes\" or \"Emergency Drugs & Equipment (Monthly)\") and choose the box.",
      "For the label: press \"Print / save label\" under the QR code on the right.",
      "For the list of contents: press \"Print contents list\" at the top.",
    ],
    tip: "Stick the label on the box. Scanning it with the Primovex app starts that box's check.",
    open: { label: "Open the boxes", route: "/inventory?tab=anaphylaxis" },
    related: ["check-kit-phone", "manage-kit"],
  },
  {
    id: "anaphylaxis-guidance",
    title: "Find the current anaphylaxis guidance",
    topic: "Kits and boxes",
    asks: ["where do i find the anaphylaxis guidance", "where is the anaphylaxis guidance", "latest anaphylaxis guidelines", "resus council anaphylaxis", "what is the anaphylaxis protocol", "adrenaline dose guidance"],
    keywords: ["guidance", "guideline", "anaphylaxis", "protocol", "resus", "nice"],
    needs: "inventory.read",
    where: "desktop",
    steps: [
      "Go to Inventory and open \"Anaphylaxis Emergency Boxes\".",
      "Scroll down to the \"Anaphylaxis guidance\" panel. It links to the Resuscitation Council UK, NICE and other guidance, with the date each was published and when the list was last checked.",
    ],
    tip: "These are links to the publishers. Always read doses and algorithms from the source.",
    open: { label: "Open the boxes", route: "/inventory?tab=anaphylaxis" },
    related: ["check-kit-phone"],
  },

  // ---- fridges and temperature -----------------------------------------------------------------------
  {
    id: "log-temperature",
    title: "Record a fridge or freezer temperature",
    topic: "Fridges",
    asks: ["how do i log a fridge temperature", "record the fridge reading", "enter the temperature", "daily fridge check", "log a temperature"],
    keywords: ["temperature", "fridge", "freezer", "log", "reading", "record"],
    needs: "temperature.write",
    where: "desktop",
    steps: [
      "Go to Temperature in the left menu.",
      "Press \"Log temperature\" and choose the fridge or freezer.",
      "Enter the reading and save. If it's outside the unit's range Primovex flags it.",
    ],
    tip: "Connected sensors record readings by themselves where they're set up.",
    open: { label: "Open Temperature", route: "/temperature" },
    related: ["fridge-out-of-range"],
  },
  {
    id: "fridge-out-of-range",
    title: "What to do when a fridge is out of range",
    topic: "Fridges",
    asks: ["how do i deal with a fridge that is out of range", "what do i do if the fridge is too warm", "fridge out of range", "temperature incident", "fridge alarm", "record a cold chain incident"],
    keywords: ["incident", "range", "warm", "cold", "breach", "excursion"],
    needs: "temperature.write",
    where: "desktop",
    steps: [
      "Check the fridge and the stock inside it, and follow the practice's cold chain procedure first.",
      "In Primovex go to Temperature and press \"New incident\" to record it, with the affected stock and the actions you took.",
      "When it's dealt with, open the incident and press \"Resolve incident\" and add the resolution notes (they're required).",
    ],
    tip: "Primovex records and reminds; the clinical decision about the stock is yours and the practice's procedure.",
    open: { label: "Open Temperature", route: "/temperature" },
    related: ["log-temperature"],
  },

  // ---- governance ------------------------------------------------------------------------------------
  {
    id: "new-sar",
    title: "Log a new subject access request (SAR)",
    topic: "SARs and concerns",
    asks: ["how do i log a sar", "new subject access request", "add a sar", "record a data request", "start a sar"],
    keywords: ["sar", "subject", "access", "request", "data"],
    needs: "governance.manageSars",
    where: "desktop",
    steps: [
      "Go to SARs in the left menu and press \"New SAR\".",
      "Fill in the date received, the request type and the patient's EMIS number (the system never stores the patient's name).",
      "Choose who it's assigned to, and the manager for escalation, from the list of colleagues.",
      "Save. Primovex works out the due date and reminds the person it's assigned to as the deadline approaches.",
    ],
    open: { label: "Open SARs", route: "/governance/sars" },
    related: ["new-concern"],
  },
  {
    id: "new-concern",
    title: "Log a new concern or complaint",
    topic: "SARs and concerns",
    asks: ["how do i log a concern", "record a complaint", "new concern", "add a patient concern", "listening to people"],
    keywords: ["concern", "complaint", "listening", "people", "pals"],
    needs: "governance.manageConcerns",
    where: "desktop",
    steps: [
      "Go to Concerns in the left menu and press \"New concern\".",
      "Fill in the details. Use the patient's EMIS number or initials and date of birth, never their name.",
      "Save, and keep the Primovex reference number with the paper file.",
    ],
    open: { label: "Open Concerns", route: "/governance/concerns" },
    related: ["new-sar"],
  },

  // ---- people and administration ---------------------------------------------------------------------------
  {
    id: "add-user",
    title: "Add a new member of staff",
    topic: "People and access",
    asks: ["how do i add a new user", "create an account for a new starter", "add a member of staff", "new user account", "set up a login"],
    keywords: ["user", "account", "starter", "login", "staff", "add", "create"],
    needs: "admin.manageUsers",
    where: "desktop",
    steps: [
      "Go to Advanced Administration and open \"Add User\".",
      "Enter their name, work email address and role, then create the account.",
      "Nobody is emailed. To let them in, go to Users, find them and press \"Reset password\" to make a sign-in link, then send it to them yourself. The link only lasts an hour, so make it when you're ready to send.",
    ],
    tip: "To add lots of people at once, use \"Import staff\" instead.",
    open: { label: "Open Add User", route: "/admin/users/add" },
    related: ["import-staff", "add-role", "reset-password"],
  },
  {
    id: "import-staff",
    title: "Add many staff at once from a spreadsheet",
    topic: "People and access",
    asks: ["how do i import staff", "add lots of users", "upload a staff list", "bulk add staff", "import a csv of staff"],
    keywords: ["import", "bulk", "spreadsheet", "csv", "upload", "staff", "many"],
    needs: "admin.manageUsers",
    where: "desktop",
    steps: [
      "Go to Advanced Administration and open \"Import staff\", then choose your staff spreadsheet (a .csv file with name, email, role, department and who they report to).",
      "Read the preview. It shows new accounts, people who already have one (only their department and reporting line are set) and anything that needs fixing. You can edit a name or role in the preview.",
      "Press the green button to create the accounts. No emails are sent.",
      "Later, give people their sign-in links yourself: Users, then \"Reset password\" next to each person.",
    ],
    open: { label: "Open Import staff", route: "/admin/users/import" },
    related: ["add-user", "set-department", "reset-password"],
  },
  {
    id: "reset-password",
    title: "Give someone a new sign-in link (or reset their password)",
    topic: "People and access",
    asks: ["how do i reset someone's password", "send a sign in link", "forgotten password", "new password link", "someone cannot log in", "reset a password"],
    keywords: ["password", "reset", "link", "locked", "forgot", "login", "sign"],
    needs: "admin.manageUsers",
    where: "desktop",
    steps: [
      "Go to Advanced Administration, open Users and find the person.",
      "Press \"Reset password\". Primovex makes a link for them to set a new password; copy it and send it to them yourself.",
      "The link only lasts an hour. If it runs out, make another.",
    ],
    tip: "If they have lost the phone with their authenticator app, press \"Reset two-step\" for them as well.",
    open: { label: "Open Users", route: "/admin/users" },
    related: ["add-user"],
  },
  {
    id: "add-role",
    title: "Create a role, or give someone different permissions",
    topic: "People and access",
    asks: ["how do i create a new role", "add a role", "make a stock controller role", "change what someone can do", "give permission to delete stock", "set up permissions"],
    keywords: ["role", "permission", "permissions", "access", "controller", "capability"],
    needs: "admin.manageRoles",
    where: "desktop",
    steps: [
      "Go to Advanced Administration and open \"Roles & Permissions\", then press \"Add Role\".",
      "Name the role. Use \"Start from\" to begin with a ready-made set (for example Stock Controller) and then tick or untick what it can do.",
      "Save, then go to Users and assign the role to the people who need it.",
    ],
    open: { label: "Open Roles & Permissions", route: "/admin/roles" },
    related: ["add-user", "archive-delete-item"],
  },
  {
    id: "set-department",
    title: "Put someone in a department, or change who they report to",
    topic: "People and access",
    asks: ["how do i set a department", "change who someone reports to", "add a department", "move someone to another department", "set up departments", "line manager"],
    keywords: ["department", "reports", "manager", "line", "team", "organisation"],
    needs: "practiceAdmin.write",
    where: "desktop",
    steps: [
      "Go to Practice Admin and open the Departments tab. To add a department, type its name at the top and press \"Add\".",
      "Scroll down to the Organisation chart. Click the person (in the chart, or under \"By department\"), choose their Department, and tick who they report to.",
      "Changes save straight away.",
    ],
    tip: "Importing staff from a spreadsheet sets departments and reporting lines for everyone in one go.",
    open: { label: "Open Practice Admin", route: "/practice-admin" },
    related: ["print-org-chart", "import-staff"],
  },
  {
    id: "print-org-chart",
    title: "Print the organisation chart, or a staff list by department",
    topic: "People and access",
    asks: ["how do i print the organisation chart", "print the org chart", "print the staff list", "print a department", "print the structure"],
    keywords: ["print", "organisation", "org", "chart", "structure", "list"],
    needs: "practiceAdmin.read",
    where: "desktop",
    steps: [
      "Go to Practice Admin, open the Departments tab and scroll to the Organisation chart.",
      "Pick the paper (A4, or A3 for a big chart).",
      "Press \"Print chart\" for everyone (or choose one department first and print just that), \"Print each department\" for one page per department, or \"Print staff list\" for a table by department.",
    ],
    tip: "Large teams are shown as a list under their manager so the chart stays readable.",
    open: { label: "Open Practice Admin", route: "/practice-admin" },
    related: ["set-department"],
  },

  // ---- security and oversight ---------------------------------------------------------------------------------
  {
    id: "activity-report",
    title: "See who has signed in and what they used",
    topic: "Security",
    asks: ["how do i see who logged in", "who has been using primovex", "login report", "see staff activity", "audit sign ins", "user activity report"],
    keywords: ["login", "logged", "signed", "activity", "report", "audit", "who", "sessions"],
    needs: "audit.read",
    where: "desktop",
    steps: [
      "Go to Security in the left menu.",
      "Press \"Sign-in & activity report\" and choose the period.",
      "You'll see each person's sign-ins, time in the app and the areas they used. Click a name for each session. Anything unusual (a sign-in at night, a very long session, two devices at once) is flagged.",
      "\"Export CSV\" saves it. Viewing and exporting are themselves recorded.",
    ],
    tip: "It records the areas of the app, never what was typed or which record was opened.",
    open: { label: "Open Security", route: "/security-centre" },
    related: ["view-audit-log"],
  },
  {
    id: "view-audit-log",
    title: "See the audit log of who did what",
    topic: "Security",
    asks: ["how do i see the audit log", "who changed this", "audit trail", "find out who did something", "view audit events"],
    keywords: ["audit", "log", "changed", "trail", "events", "who"],
    needs: "audit.read",
    where: "desktop",
    steps: [
      "Go to Security in the left menu and press \"View audit events\".",
      "Choose a period, then search by action, person or record.",
      "\"Evidence JSON\" or \"CSV\" saves what you're looking at.",
    ],
    open: { label: "Open Security", route: "/security-centre" },
    related: ["activity-report"],
  },
  {
    id: "two-step-sign-in",
    title: "Set up two-step sign-in (authenticator app)",
    topic: "Security",
    asks: ["how do i set up two step", "turn on mfa", "authenticator app", "two factor login", "extra security for my login"],
    keywords: ["two", "step", "mfa", "authenticator", "factor", "2fa", "code"],
    where: "both",
    steps: [
      "Two-step sign-in is built but hasn't been switched on for the practice yet, so you can't set it up today.",
      "When it is, you'll find it under Security (\"Your sign-in security\") on a computer, and on the \"Me\" tab on the phone.",
    ],
    tip: "Ask an administrator when it's planned.",
    related: ["reset-password"],
  },
  {
    id: "orb-ai-settings",
    title: "Turn the Orb's AI on or off",
    topic: "The Orb",
    asks: ["how do i turn on the orb ai", "switch off the ai", "orb language assistant", "enable ai wording", "orb settings"],
    keywords: ["orb", "ai", "language", "assistant", "wording", "switch"],
    needs: "admin.access",
    where: "desktop",
    steps: [
      "Go to Advanced Administration and open \"Orb Learning\".",
      "At the top are two switches: one lets the Orb understand questions in your own words, the other lets it reword its answers. Each has its own tick-box confirming you've checked the Azure region and the DPIA.",
      "\"Turn off\" takes effect straight away.",
    ],
    open: { label: "Open Orb Learning", route: "/admin/orb-learning" },
    related: ["what-can-orb-do"],
  },

  // ---- general -----------------------------------------------------------------------------------------------------
  {
    id: "what-can-orb-do",
    title: "What can I ask the Orb?",
    topic: "The Orb",
    asks: ["how do i use the orb", "what can you do", "what can i ask", "help", "what questions can i ask", "what do you know"],
    keywords: ["orb", "ask", "help", "can", "questions", "use"],
    where: "both",
    steps: [
      "Ask in your own words about stock (\"is anything low?\", \"what's expiring?\", \"do we have any dressings?\"), fridges (\"are the fridges OK?\"), cleaning (\"which rooms haven't been cleaned?\"), alerts, tasks, maintenance, emergency kits and anaphylaxis boxes, and how the practice is doing overall.",
      "Ask \"how do I...\" for step-by-step help, for example \"how do I move stock into a kit?\".",
      "Managers can ask management questions: \"when was the last fire alarm test?\", \"what are the tap water temps in the last month?\", \"when did Craig last log in?\", \"how many SARs does he have outstanding?\", \"where are we up to with concerns?\", or \"what needs attention before I leave?\" for an end-of-day briefing.",
      "It can also get things ready for you to confirm: \"I've taken two gloves from the store cupboard\", \"I've received 20 chlorphenamine, batch 4471, expires March 2028\", \"count the nurses room: gloves 12, syringes 40\", \"take the expired stock off\", \"remind me to check the fridge tomorrow at 9\" or \"tell Ben the vaccine fridge needs checking\". It shows a card and nothing changes until you press Confirm (or say \"yes\").",
      "Say \"go to purchase orders\" or \"open the alerts\" and it takes you there.",
      "Answers show where they came from, and it only tells you and does what your permissions allow.",
    ],
    related: ["talk-to-orb-phone", "record-fridge-temperature", "add-stock-item", "check-kit-phone", "log-temperature"],
  },
  {
    id: "record-fridge-temperature",
    title: "Record a fridge temperature on the phone",
    topic: "Temperature",
    asks: ["how do i record a fridge temperature", "fridge check on my phone", "do the fridge temperatures", "scan the fridge tag", "record min and max temperature", "reset the fridge thermometer"],
    keywords: ["fridge", "temperature", "thermometer", "min", "max", "reset", "check", "scan", "tag", "qr"],
    needs: "temperature.write",
    where: "phone",
    steps: [
      "Tap the NFC tag on the fridge with your phone, or press \"Fridge check\" on your home screen and scan the QR code stuck on the fridge.",
      "Read the thermometer on the fridge. Type the current temperature, then press Next. Use the ± button for a minus.",
      "Press MIN on the thermometer and type the minimum, then MAX and type the maximum.",
      "Press the reset button on the thermometer and tick \"I've pressed reset\".",
      "Check the summary. It says in range or outside the safe range. Press \"Save check\". Your name and the time are added for you.",
      "If it is outside the safe range, tick what you have done (checked the door, moved the stock, and so on). The Practice Manager and the nurse lead are told straight away, so you don't need to go and find them.",
    ],
    tip: "There is one check each morning and each afternoon per fridge. A second one is only allowed after a reading that was out of range, to show it has recovered.",
    related: ["fridge-alerts-setup"],
  },
  {
    id: "fridge-alerts-setup",
    title: "Set up the fridges and who is alerted when one is out of range",
    topic: "Temperature",
    asks: ["how do i set up the fridges", "add a fridge", "set the safe temperature range for a fridge", "who gets told when a fridge is out of range", "fridge alerts", "quarantine a fridge", "clear a fridge incident"],
    keywords: ["fridge", "range", "alert", "quarantine", "incident", "nurse", "manager", "setup", "clear"],
    needs: "practiceAdmin.write",
    where: "desktop",
    steps: [
      "Go to Temperature and open the \"Fridges\" tab (you only see it if you can set fridges up).",
      "Press \"Add a fridge\", give it a name, choose its site and kind. The usual safe range is filled in (2 to 8 °C for a fridge); change it if the fridge needs a different one.",
      "Press \"Print QR label\" on a fridge (or \"Print all QR labels\") and stick the label on the fridge. Scanning it with the Primovex app opens that fridge's temperature check. For an NFC tag instead, open the phone app, go to Facilities > Practice spaces > Fridges, choose the fridge and press \"Write this fridge to an NFC tag\".",
      "Under \"Who is alerted\", tick the roles that should be told when a reading is out of range. The Practice Manager is ticked to start with. Add a Nurse Manager role under Practice Admin > Roles, give it \"Resolve temperature incidents\", then tick it here.",
      "When a reading is out of range, the people ticked get a message on their screen with \"Take action\": Quarantine this fridge, Record stock moved or discarded, and Clear it and return to use. A fridge can only be cleared after a recheck that is back in range.",
    ],
    open: { label: "Open Temperature", route: "/temperature" },
    related: ["record-fridge-temperature"],
  },
  {
    id: "coshh-register",
    title: "Keep the COSHH register: hazardous products, PPE, first aid and safety data sheets",
    topic: "Compliance",
    asks: ["how do i add a cleaning product to coshh", "coshh register", "add a safety data sheet", "where do i upload an sds", "coshh review is overdue", "print coshh labels for the cleaning cupboard", "what is coshh"],
    keywords: ["coshh", "chemical", "hazardous", "substance", "sds", "safety data sheet", "ppe", "cupboard", "cleaning", "review"],
    needs: "coshh.manage",
    where: "desktop",
    steps: [
      "Go to Compliance and open the \"COSHH\" tab.",
      "Press \"Add a substance\". Type the product name as it is on the label, choose the supplier, tick the hazards, the protective equipment and the first aid steps, and choose where it is kept (the site and room come from Practice Admin).",
      "Attach the supplier's safety data sheet (a PDF; the supplier gives you this and it is on their website) and check the review date. A year from today is filled in.",
      "Press \"Print cupboard labels\" and stick the QR label on each cupboard. Scanning it with the Primovex app lists what is kept in that cupboard, what to wear, and what to do if there is a splash or a spill.",
      "When you have looked at a product again, press \"Mark as reviewed\" and the next review moves on a year. The Practice Manager, partners and you are told on the phone home when a review is overdue or coming up in the next 30 days.",
      "Cleaners, partners and the practice manager look things up on their phone under \"Chemicals (COSHH)\". Nobody can delete a product, only archive it, so the history stays.",
    ],
    tip: "COSHH means Control of Substances Hazardous to Health. Review each product at least once a year, or sooner if the product or how it is used changes.",
    open: { label: "Open Compliance", route: "/compliance" },
    related: [],
  },
  {
    id: "inspection-pack",
    title: "Get ready for a HEIW visit or a Health and Safety visit",
    topic: "Reports",
    asks: ["how do i prepare for a heiw visit", "print a report for the inspection", "health and safety visit report", "evidence pack for inspectors", "how do i save the inspection report as a pdf", "what do i need for an inspection"],
    keywords: ["inspection", "heiw", "health and safety", "evidence", "pack", "pdf", "visit", "inspector", "report", "summary"],
    needs: "reports.inspection",
    where: "desktop",
    steps: [
      "Ask the Orb on the desktop: \"We have a HEIW visit, print off a report ready\". It opens the Inspection pack for that visit. Or open Inspection pack from the menu and choose the visit.",
      "Read \"To put right before the visit\" at the top. Each line says what is out of date or missing, such as a fire check that is overdue, a fridge incident still open, or a COSHH review that is overdue.",
      "Each area below shows the evidence Primovex holds: how many checks, when the last one was, and anything that failed. An area marked \"Not shown\" is one your role can't read; ask the Practice Manager to run it.",
      "Press \"Print or save as PDF\". In the print window choose \"Save as PDF\" as the printer to keep a copy, or your printer to print it.",
      "The sheet ends with what is kept outside Primovex (risk assessments in Croner, the training matrix) so you remember to bring it.",
    ],
    tip: "Concerns, SARs and significant events are shown as counts only, never names or patient details. Press Refresh after you fix something to see the sheet update.",
    open: { label: "Open Inspection pack", route: "/inspection" },
    related: ["coshh-register"],
  },
  {
    id: "stock-take",
    title: "Do a full stock take with the team on their phones",
    topic: "Inventory",
    asks: ["how do i do a stock take", "request a stock take", "count the stock with the team", "how do i count a room on my phone", "review stock take differences", "start my own stock take", "stocktake"],
    keywords: ["stock", "take", "stocktake", "count", "physical", "claim", "scan", "differences", "review", "team"],
    needs: "stocktake.count",
    where: "phone",
    steps: [
      "To count (phone): open the Stock take tile on the home screen, or tap the banner that says a stock take needs your help. Pick the stock take, then tap \"Count this\" on a room or cupboard that is free. Others see it is yours, so nobody counts it twice.",
      "Scan each product's barcode or search for it by name, then type how many are really there. The number the system expects is hidden on purpose. If nothing is there, tap \"None here (0)\".",
      "If you find something that is not in the system, tap \"Something not in the system\" and enter what it is and how many. It goes to the manager; it does not change stock by itself.",
      "Tap \"Finish this place\" when you are done. If items on the list were not counted it tells you. Take another place, or \"Give this place back\" if you cannot finish.",
      "To do one yourself without being asked: Stock take, then \"Start my own stock take\", choose the places and count them the same way.",
      "To request one (Practice Manager, or a role given \"Request, review and apply a stock take\"): on the desktop go to Stock take, press \"Request a stock take\", choose the places, who is asked and a finish-by date.",
      "To review: open the stock take on the desktop. Large differences are marked. Tick the changes you accept and press \"Apply\"; stock only changes then, and each change is logged. \"Print results\" gives a sheet for your records.",
    ],
    tip: "A find in a room's main store that is recorded in another place is only reported; move it with Inventory afterwards. Stock moves while people count, so the review compares to what is recorded now.",
    open: { label: "Open Stock take", route: "/stocktake" },
    related: [],
  },
  {
    id: "talk-to-orb-phone",
    title: "Talk to the Orb on the phone when your hands are busy",
    topic: "The Orb",
    asks: ["how do i talk to the orb", "voice orb", "how do i use voice", "orb keeps stopping listening", "how do i end the conversation", "speak to the orb", "hands free orb", "how do i take several items from stock quickly", "say yes to confirm"],
    keywords: ["voice", "talk", "speak", "listening", "microphone", "hands", "conversation", "yes", "confirm"],
    where: "phone",
    steps: [
      "Open the Orb and tap the glowing orb (or the microphone) once. It says \"Listening\" and keeps listening after every answer, so you can carry on without tapping again.",
      "Take several items in one go: \"I've taken two chlorphenamine, one adrenaline and a box of gloves from the store cupboard\". You get one card. Say \"and two more gloves\" to add to it.",
      "When a card appears, say \"yes\" or \"go ahead\" to confirm, or \"cancel\". When it asks you to choose (a batch, a place, how much harm), say what's on the button, like \"low harm\" or \"the second one\".",
      "To finish, say \"that's all\", \"thanks\" or \"stop\", or just stay quiet for about 15 seconds. Tap the orb to end it at any time.",
      "Under the orb, \"Spoken answers\" switches on short spoken replies.",
    ],
    tip: "The phone app listens when you tap it. It doesn't wake up to the word \"Orb\".",
    related: ["what-can-orb-do"],
  },
  {
    id: "find-notifications",
    title: "Where do I see my notifications and reminders?",
    topic: "The Orb",
    asks: ["where do i see my notifications", "where are my notifications", "how do i see my reminders", "where do messages go", "notification bell", "my alerts"],
    keywords: ["notification", "notifications", "bell", "reminder", "message", "inbox"],
    where: "both",
    steps: [
      "A message from a colleague appears in the middle of the screen, on the desktop app and on the phone, when it arrives or when you sign in. It shows who sent it and what it says.",
      "Press a quick reply (\"Done\", \"On it\", \"Will do\"), or \"Reply\" to type a short one. Replies can't contain numbers, dates, email addresses or phone numbers, so patient details can't go in by mistake. Press \"Dismiss\" when you've read it, or \"Snooze\" to be reminded in an hour, later today or tomorrow morning.",
      "The cross just puts it aside for now. On the phone a \"Messages\" button brings it back.",
      "On a computer you can also press the \"Notifications\" bell at the top right to see everything, including deadline reminders (SARs and concerns) and your own \"remind me later\" reminders.",
    ],
    open: { label: "Open notifications", route: "/notifications" },
    related: ["check-kit-phone"],
  },
  {
    id: "orb-stock-actions",
    title: "Can the Orb find stock, message a team or raise a reorder?",
    topic: "The Orb",
    asks: ["how can the orb order stock", "how do i tell the hca team something", "how do i message a team", "how do i raise a reorder with the orb", "how can the orb find stock", "how do i ask the orb where stock is"],
    keywords: ["orb", "stock", "team", "message", "reorder", "order", "where", "needles"],
    where: "desktop",
    steps: [
      "Where is it: ask \"where are the blue needles?\", \"how many adrenaline are in anaphylaxis box 3?\" or \"what's in the emergency trolley?\". This only looks, it changes nothing.",
      "Message a team: say \"tell the HCA team BD blue needles need ordering\". A team is everyone with that role in Primovex. The Orb shows the message on a card and sends it only when you press Send message.",
      "Reorder: say \"BD blue needles need ordering\" or \"reorder 5 chlorphenamine\". The card shows the product and quantity; Request reorder puts it in the Reorder Centre for approval. Nothing is ordered from a supplier.",
      "You need permission to change stock for the last two. Messages can't contain numbers, dates, emails or phone numbers, so never put patient details in one. Team messages show in the desktop notifications bell.",
    ],
    open: { label: "Open Reorder Centre", route: "/reorder-centre" },
    related: ["find-notifications", "what-can-orb-do"],
  },
  {
    id: "limit-orb-topics",
    title: "How do I limit what the Orb and Pulse orb show a person?",
    topic: "Admin",
    asks: ["how do i limit what the orb shows someone", "how do i restrict the orb for a user", "how do i stop someone asking the orb about stock", "how do i set what the pulse orb shows a person", "how do i make the orb only answer about sars"],
    keywords: ["orb", "pulse", "limit", "restrict", "topics", "only", "user", "scope"],
    where: "desktop",
    steps: [
      "Go to Admin, then Users, and press \"Orb\" next to the person's name.",
      "Choose \"Only these topics\" and tick what they should have, for example just SARs and concerns, or just Compliance. Press Save.",
      "From then on the Orb only answers questions about those topics for them, and their Pulse orb only shows and scores those areas. \"How do I...?\" help always stays.",
      "This only narrows what their role allows; it never gives anyone more. To give them more access, change their role instead. Choose \"Everything their role allows\" to remove the limit.",
    ],
    open: { label: "Open Users", route: "/admin/users" },
    related: ["what-can-orb-do"],
  },
  {
    id: "stock-review-alerts",
    title: "How do I see stock that is not being used, or that we have too much or too little of?",
    topic: "Stock",
    asks: ["how do i see stock that has not been used for a long time", "how do i find out if we have too much stock", "how do i see which stock may run short", "how do i do a stock take on an item that has not been used"],
    keywords: ["stock", "review", "unused", "overstocked", "too much", "too little", "stock take", "dormant", "short"],
    where: "desktop",
    steps: [
      "Open Alerts and scroll to Stock review. It is checked every morning against how fast each item has really been used over the past year.",
      "Needs a stock take: nothing has been recorded for six months or more. The person who last handled it gets a message asking them to count what is on the shelf and update Primovex. Open the item and set the count.",
      "Looks like too much: it would last more than a year at the usual rate. Around that many would do. May run short: it would last under three weeks, or the minimum is too low for how fast it goes.",
      "Stock controllers also get a short summary every Monday. Emergency drugs, emergency equipment and kit stock are left out because they are meant to sit unused.",
    ],
    open: { label: "Open Alerts", route: "/alerts" },
    related: ["orb-record-stock-used"],
  },
  {
    id: "orb-teach-names",
    title: "How do I teach the Orb the names we use for our stock?",
    topic: "The Orb",
    asks: ["how do i teach the orb a name for a product", "how do i teach the orb our nicknames for stock", "how do i make the orb understand a medicine name", "how do i add a name the orb should recognise"],
    keywords: ["orb", "teach", "name", "nickname", "alias", "product", "medicine", "brand"],
    where: "desktop",
    steps: [
      "The Orb already knows common medicine names: generic and brand names (for example Piriton for chlorphenamine), US spellings and small spelling slips.",
      "For names only your practice uses, go to Admin, then Orb, and find Names for your stock.",
      "Type what people say (for example \"emergency injector\"), pick the product it means from the list, and press Teach it. You need permission to verify stock.",
      "From then on the Orb treats that phrase as that product when someone asks about it or records using it.",
    ],
    open: { label: "Open Orb settings", route: "/admin/orb-learning" },
    related: ["orb-record-stock-used"],
  },
  {
    id: "orb-record-stock-used",
    title: "How do I record stock I've used with the Orb?",
    topic: "The Orb",
    asks: ["how do i record stock i have used with the orb", "how do i tell the orb i took an ampoule", "how do i take stock off using the orb", "how do i tell the orb which batch i took"],
    keywords: ["orb", "ampoule", "batch", "taken", "took"],
    where: "both",
    steps: [
      "Tell the Orb what you took, for example \"I've just taken one adrenaline from room D62\" or \"one adrenaline ampoule from the store cupboard\". You need permission to change stock.",
      "If you haven't said where from, it lists the places that have it. If there is more than one batch, it asks which: tap the one whose batch number ends the same as the pack in your hand.",
      "It shows a card: the product, how many, where from, the batch and the stock left afterwards. Press Take it off stock to record it. Nothing changes until you do.",
      "It's recorded the same as using stock on the Inventory page, with the batch you chose, and shows in the stock history.",
    ],
    open: { label: "Open Inventory", route: "/inventory" },
    related: ["orb-stock-actions"],
  },
  {
    id: "report-significant-event",
    title: "How do I report a significant event?",
    topic: "Governance",
    asks: ["how do i report a significant event", "how do i log an incident", "how do i report a near miss", "how do i raise a significant event", "how do i report something that went wrong"],
    keywords: ["significant", "event", "incident", "near", "miss", "report", "learning", "se"],
    where: "both",
    steps: [
      "Anyone can do this. On a computer: Significant events in the left menu, then Report. On the phone: Significant events on the Home screen, then Report.",
      "Give it a short title, the date, where it happened (pick the room) and how much harm it caused. Say what happened and what was done straight away.",
      "Never use anyone's name. Use roles (the nurse, a receptionist). If a patient was involved, give their EMIS number, or initials and date of birth if there isn't one.",
      "Or tell the Orb: say \"report a significant event: the wrong vaccine was drawn up in Treatment Room 1 yesterday, no harm\". It sets the report up for you to check, and nothing is sent until you press Report event. No names, and use an EMIS number for any patient.",
      "The significant events team is told. You can follow what happens to it under \"Reported by me\", and add notes.",
    ],
    open: { label: "Open Significant events", route: "/governance/significant-events" },
    related: ["run-significant-event"],
  },
  {
    id: "run-significant-event",
    title: "How do I investigate and review a significant event, and record the meeting?",
    topic: "Governance",
    asks: ["how do i investigate a significant event", "how do i run a significant event meeting", "how do i record minutes for a significant event", "how do i ask people to review a significant event", "how do i close a significant event", "how do i set who reviews significant events"],
    keywords: ["significant", "event", "investigate", "review", "reviewer", "meeting", "minutes", "actions", "close", "triage"],
    where: "both",
    steps: [
      "You need the significant events team permission. Open the event and choose Investigate, or No investigation needed (and say why). Pick who leads the investigation.",
      "When the investigation is finished, press Ask for reviews. People in your usual reviewer roles are ticked for you; add or remove anyone. Each reviewer writes their own view. Set the usual roles under the Settings tab.",
      "Press Ready for the meeting, then create a meeting under Meetings, add the events to its agenda, write the discussion for each event and the minutes, add actions (who, by when), and press The meeting has been held. Copy or print the minutes.",
      "Actions can be ticked off by their owner. When none are open, press Close on the event.",
    ],
    open: { label: "Open Significant events", route: "/governance/significant-events" },
    related: ["report-significant-event"],
  },
  {
    id: "sars-on-phone",
    title: "How do I see SARs on my phone?",
    topic: "Governance",
    asks: ["how do i see sars on my phone", "how do i open sars on mobile", "how do i add a sar on my phone", "how do i check a sar on the phone app"],
    keywords: ["sar", "sars", "phone", "mobile", "subject", "access", "request"],
    where: "phone",
    steps: [
      "On the Home screen of the phone app, press SARs. You need access to governance to see the tile.",
      "The SAR team sees every request, can add one with +, change its status, tick the checks and add notes. Anyone else sees only requests assigned to them.",
      "It uses the same PIN or fingerprint lock as Concerns, because SARs hold patient information.",
    ],
    related: ["report-significant-event"],
  },
  {
    id: "screen-locked",
    title: "My screen locked and asks for a PIN",
    topic: "Security",
    asks: ["how do i unlock the screen", "why has it locked", "what is the pin", "forgot my pin", "screen lock", "idle lock"],
    keywords: ["lock", "locked", "pin", "idle", "timeout"],
    where: "both",
    steps: [
      "Primovex locks itself after 15 minutes without use, to protect patient and practice information on a shared screen.",
      "Enter the PIN you set to carry on. If you've forgotten it, use \"Sign out instead\" and sign in again with your password.",
      "Whatever you were doing is still there afterwards. Everyone is signed out automatically after 12 hours.",
    ],
    related: ["reset-password"],
  },
];
